---
#apiVersion: v1
#kind: Namespace#
#metadata:
#   name: istio-ingress
#---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-istiod
      namespace: istio-system
  chart:
    spec:
      chart: gateway
      version: 1.25.3
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  interval: 1m
