---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-istiod
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: istiod
      version: 1.25.3
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 1m