---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-traefik
  namespace: istio-system
spec:
  chart:
    spec:
      chart: istio/base
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 1m