---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  chart:
    spec:
      chart: gateway
      version: 1.25.3
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  interval: 1m
  values:
    service:
      # Set the service type to LoadBalancer to expose it externally
      type: LoadBalancer
      ports:
      - name: http
        port: 80
        targetPort: 80
        protocol: TCP
      - name: https
        port: 443
        targetPort: 443
        protocol: TCP
    # Enable hostNetwork to bind directly to host network interfaces
    gateways:
      istio-ingressgateway:
        name: istio-ingressgateway
        namespace: istio-ingress
        enabled: true
        # Use host network to bind directly to port 80/443 on the node
        hostNetwork: true
        # Ensure proper kubernetes.io/ingress.class label
        labels:
          istio: ingressgateway
          app: istio-ingressgateway
