apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: prometheus
spec:
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: bitnamicharts/kube-prometheus
      version: 11.1.11
      sourceRef:
        kind: HelmRepository
        name: dockerhub
        namespace: default
  interval: 1m
  values:
    global:
    prometheus:
      retention: 10d
      resourcesPreset: medium
      persistence:
        enabled: true
        size: 5Gi
