apiVersion: v1
kind: Namespace
metadata:
  labels:
    foobar:test
  name: prometheus
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: prometheus
spec:
  chart:
    spec:
      chart: kube-prometheus
      version: 1.25.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
  interval: 1m
  values:
    global:
    prometheus:
      retention: 10d
      resourcesPreset: medium
      persistence:
        enabled: true
        size: 5Gi
        storageClass: ems-default
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-virtualservice
  namespace: prometheus
spec:
  hosts:
    - "*"
  gateways:
    - prometheus-gateway
  http:
    - name: kube-prometheus-prometheus
      route:
        - destination:
            host: kube-prometheus-prometheus
            port:
              number: 9090
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: prometheus-gateway
  namespace: prometheus
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: MUTUAL
        credentialName: ems-int
      hosts:
        - "prometheus.int.api-ems.prod.deutschepost.de"