apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: prometheus
spec:
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: bitnamicharts/kube-prometheus
      version: 11.1.11
      sourceRef:
        kind: HelmRepository
        name: dockerhub
        namespace: default
  interval: 1m
  values:
    global:
    prometheus:
      retention: 10d
      resourcesPreset: medium
      persistence:
        enabled: true
        size: 5Gi
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-virtualservice
  namespace: prometheus
spec:
  hosts:
    - "*"
  gateways:
    - prometheus-gateway
  http:
    - name: kube-prometheus-prometheus
      route:
        - destination:
            host: kube-prometheus-prometheus
            port:
              number: 9090
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: prometheus-gateway
  namespace: prometheus
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
      - "static.69.93.203.116.clients.your-server.de"
